name: hn_app
description: A new Flutter application.

version: 0.0.2+2

environment:
  sdk: ">=2.9.2 <3.0.0"

dependencies:
  moor_flutter: ^2.1.0
  url_launcher: ^5.0.2

  built_collection: ^4.2.2
  built_value: ^7.0.6

  google_fonts: ^1.0.0

  http: ^0.12.0+2

  logging: ">=0.11.4 <2.0.0"

  font_awesome_flutter: ^8.4.0

  webview_flutter: ^0.3.7+1

  provider: ^2.0.1

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  shared_preferences: ^0.5.2+1

dev_dependencies:
  build_resolvers: ^1.3.11
  build_runner: ^1.9.0
  built_value_generator: ^7.0.6
  moor_generator: ^2.1.0

  test: ^1.15.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  analyzer: '0.39.14'

flutter:

  uses-material-design: true

  fonts:
    - family: Garamond
      fonts:
      - asset: fonts/EBGaramond-Regular.ttf
      - asset: fonts/EBGaramond-Italic.ttf
        style: italic
      - asset: fonts/EBGaramond-Bold.ttf
        weight: 700
      - asset: fonts/EBGaramond-BoldItalic.ttf
        weight: 700
        style: italic
